### ISSUE TITLE
[BUG] Operator does not start job if no secret was provided

### ISSUE THREAD

**Issue by s-vitaliy** [SneaksAndData/arcane-operator#60]
### Description

````
[11:39:35 ERR] Failed to send job
k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'UnprocessableEntity', response body {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Job.batch \"openaq-air-quality\" is invalid: [spec.template.spec.containers[0].envFrom: Invalid value: \"\": may not have more than one field specified at a time, spec.template.spec.containers[0].volumeMounts[0].name: Not found: \"apmsocketpath\"]","reason":"Invalid","details":{"name":"openaq-air-quality","group":"batch","kind":"Job","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"\": may not have more than one field specified at a time","field":"spec.template.spec.containers[0].envFrom"},{"reason":"FieldValueNotFound","message":"Not found: \"apmsocketpath\"","field":"spec.template.spec.containers[0].volumeMounts[0].name"}]},"code":422}

   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.IBatchV1Operations_CreateNamespacedJobWithHttpMessagesAsync[T](V1Job body, String namespaceParameter, String dryRun, String fieldManager, String fieldValidation, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.AbstractKubernetes.k8s.IBatchV1Operations.CreateNamespacedJobWithHttpMessagesAsync(V1Job body, String namespaceParameter, String dryRun, String fieldManager, String fieldValidation, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.BatchV1OperationsExtensions.CreateNamespacedJobAsync(IBatchV1Operations operations, V1Job body, String namespaceParameter, String dryRun, String fieldManager, String fieldValidation, Nullable`1 pretty, CancellationToken cancellationToken)
   at Snd.Sdk.Tasks.TaskExtensions.Map[TSource,TResult](Task`1 task, Func`2 selector)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Snd.Sdk.Tasks.TaskExtensions.TryMap[TSource,TResult](Task`1 task, Func`2 selector, Func`2 errorHandler)
```

### Steps to reproduce the issue

1. Create stream for public API without auth
2. Arcane does not start job



### Describe the results you expected

Job should be started

### System information

pre-2.0

**Comment by s-vitaliy** [comment]
The job was actually invalid and the operator behavior was correct. Closing the issue
